# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatRoomWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import movableLabel


class Ui_ChatRoomWin(object):
    def setupUi(self, ChatRoomWin):
        ChatRoomWin.setObjectName("ChatRoomWin")
        ChatRoomWin.resize(1161, 752)
        ChatRoomWin.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatRoomWin)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(ChatRoomWin)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color : #00a884;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar{\n"
"    border: none;\n"
"    background: rgba(0,0,0,0);\n"
"    width: 7px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle{    \n"
"    background-color: #00a884; /* whatsapp color */\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:hover{    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::handle:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line{\n"
"    border: none;\n"
"    background-color: #00a884;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:hover {    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::sub-line:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line{\n"
"    border: none;\n"
"    background-color: #00a884;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:hover {    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::add-line:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page{\n"
"    background: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.chatSide = QtWidgets.QWidget(self.widget)
        self.chatSide.setStyleSheet("QWidget#chatSide{\n"
"    background-color : #222e35;\n"
"    image: url(:/newPrefix/Icons/zagel copy.png);\n"
"    border : 0px;\n"
"}")
        self.chatSide.setObjectName("chatSide")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.chatSide)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.chatSide, 1, 1, 1, 1)
        self.titleBar = QtWidgets.QWidget(self.widget)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 40))
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleBar.setStyleSheet("QWidget#titleBar{\n"
"border-radius : 15px;\n"
"}\n"
"QPushButton{\n"
"border-radius : 10px;\n"
"}\n"
"")
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.titleBar)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setStyleSheet("image: url(:/newPrefix/Icons/zagel copy.png);")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label = movableLabel.MovableLabel(self.titleBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color : rgba(255,255,255,240);")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.min = QtWidgets.QPushButton(self.titleBar)
        self.min.setMinimumSize(QtCore.QSize(20, 20))
        self.min.setMaximumSize(QtCore.QSize(20, 20))
        self.min.setStyleSheet("QPushButton{\n"
"background-color : rgba(0,170,0,255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color : rgba(0,170,0,200);\n"
"}")
        self.min.setText("")
        self.min.setObjectName("min")
        self.horizontalLayout_5.addWidget(self.min)
        self.max = QtWidgets.QPushButton(self.titleBar)
        self.max.setMinimumSize(QtCore.QSize(20, 20))
        self.max.setMaximumSize(QtCore.QSize(20, 20))
        self.max.setStyleSheet("QPushButton{\n"
"background-color :rgba(240, 136, 0 ,255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : rgba(240 ,136, 0, 200);\n"
"}")
        self.max.setText("")
        self.max.setObjectName("max")
        self.horizontalLayout_5.addWidget(self.max)
        self.close = QtWidgets.QPushButton(self.titleBar)
        self.close.setMinimumSize(QtCore.QSize(20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("QPushButton{\n"
"background-color : rgba(240,0,0,255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : rgb(200, 0, 0);\n"
"}")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout_5.addWidget(self.close)
        self.gridLayout.addWidget(self.titleBar, 0, 0, 1, 2)
        self.controlSide = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlSide.sizePolicy().hasHeightForWidth())
        self.controlSide.setSizePolicy(sizePolicy)
        self.controlSide.setMinimumSize(QtCore.QSize(370, 0))
        self.controlSide.setStyleSheet("")
        self.controlSide.setObjectName("controlSide")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.controlSide)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ChatRooms = QtWidgets.QWidget(self.controlSide)
        self.ChatRooms.setObjectName("ChatRooms")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ChatRooms)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.controlBar = QtWidgets.QWidget(self.ChatRooms)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlBar.sizePolicy().hasHeightForWidth())
        self.controlBar.setSizePolicy(sizePolicy)
        self.controlBar.setMinimumSize(QtCore.QSize(0, 85))
        self.controlBar.setMaximumSize(QtCore.QSize(16777215, 85))
        self.controlBar.setStyleSheet("QWidget#controlBar{\n"
"background-color : #202c33;\n"
"}")
        self.controlBar.setObjectName("controlBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controlBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.profilePhotoFrame = QtWidgets.QFrame(self.controlBar)
        self.profilePhotoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profilePhotoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profilePhotoFrame.setObjectName("profilePhotoFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.profilePhotoFrame)
        self.horizontalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.profilePhoto = QtWidgets.QPushButton(self.profilePhotoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profilePhoto.sizePolicy().hasHeightForWidth())
        self.profilePhoto.setSizePolicy(sizePolicy)
        self.profilePhoto.setMinimumSize(QtCore.QSize(70, 70))
        self.profilePhoto.setMaximumSize(QtCore.QSize(70, 70))
        self.profilePhoto.setStyleSheet("QPushButton#profilePhoto{\n"
"border-image : url(:/newPrefix/Icons/5a5afbe8-1228-405d-aa18-9fb0a8cade25.jpg);\n"
"border-radius : 35px;\n"
"}")
        self.profilePhoto.setText("")
        self.profilePhoto.setObjectName("profilePhoto")
        self.horizontalLayout_4.addWidget(self.profilePhoto, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.profilePhotoFrame)
        self.statusButton = QtWidgets.QPushButton(self.controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusButton.sizePolicy().hasHeightForWidth())
        self.statusButton.setSizePolicy(sizePolicy)
        self.statusButton.setMinimumSize(QtCore.QSize(60, 60))
        self.statusButton.setStyleSheet("background-color : rgba(0,0,0,0);\n"
"")
        self.statusButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/clipart1605100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statusButton.setIcon(icon)
        self.statusButton.setIconSize(QtCore.QSize(25, 25))
        self.statusButton.setObjectName("statusButton")
        self.horizontalLayout_2.addWidget(self.statusButton, 0, QtCore.Qt.AlignRight)
        self.newChatButton = QtWidgets.QPushButton(self.controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newChatButton.sizePolicy().hasHeightForWidth())
        self.newChatButton.setSizePolicy(sizePolicy)
        self.newChatButton.setMinimumSize(QtCore.QSize(60, 60))
        self.newChatButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.newChatButton.setStatusTip("")
        self.newChatButton.setStyleSheet("background-color : rgba(0,0,0,0);\n"
"")
        self.newChatButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/plus-icon-transparent-5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newChatButton.setIcon(icon1)
        self.newChatButton.setIconSize(QtCore.QSize(25, 25))
        self.newChatButton.setObjectName("newChatButton")
        self.horizontalLayout_2.addWidget(self.newChatButton, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.addWidget(self.controlBar)
        self.chatRoomFrame = QtWidgets.QFrame(self.ChatRooms)
        self.chatRoomFrame.setStyleSheet("QWidget#chatRoomFrame{\n"
"    background-color: #111b21;\n"
"}")
        self.chatRoomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatRoomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatRoomFrame.setObjectName("chatRoomFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chatRoomFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchRoomFrame = QtWidgets.QFrame(self.chatRoomFrame)
        self.searchRoomFrame.setStyleSheet("QFrame#searchRoomFrame{\n"
"background-color : #222d34;\n"
"margin-left : 10px;\n"
"margin-right : 10px;\n"
"margin-top : 7px;\n"
"margin-bottom : 7px;\n"
"border-radius : 15px;\n"
"}\n"
"QPushButton{\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QLineEdit{\n"
"background-color : rgba(0,0,0,0);\n"
"color : rgba(255,255,255,200);\n"
"border:None;\n"
"}")
        self.searchRoomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchRoomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchRoomFrame.setObjectName("searchRoomFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.searchRoomFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchButton = QtWidgets.QPushButton(self.searchRoomFrame)
        self.searchButton.setStyleSheet("")
        self.searchButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon2)
        self.searchButton.setIconSize(QtCore.QSize(25, 25))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.searchLine = QtWidgets.QLineEdit(self.searchRoomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLine.sizePolicy().hasHeightForWidth())
        self.searchLine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLine.setFont(font)
        self.searchLine.setObjectName("searchLine")
        self.horizontalLayout_3.addWidget(self.searchLine)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 8)
        self.verticalLayout_3.addWidget(self.searchRoomFrame)
        self.scrollArea = QtWidgets.QScrollArea(self.chatRoomFrame)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border:none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.ScrollRooms = QtWidgets.QWidget()
        self.ScrollRooms.setGeometry(QtCore.QRect(0, 0, 368, 559))
        self.ScrollRooms.setStyleSheet("QWidget#ScrollRooms{\n"
"    background-color: #111b21;\n"
"}")
        self.ScrollRooms.setObjectName("ScrollRooms")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ScrollRooms)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.ScrollRooms)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.chatRoomFrame)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 14)
        self.verticalLayout_5.addWidget(self.ChatRooms)
        self.gridLayout.addWidget(self.controlSide, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 7)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(ChatRoomWin)
        QtCore.QMetaObject.connectSlotsByName(ChatRoomWin)

    def retranslateUi(self, ChatRoomWin):
        _translate = QtCore.QCoreApplication.translate
        ChatRoomWin.setWindowTitle(_translate("ChatRoomWin", "Form"))
        self.label.setText(_translate("ChatRoomWin", "Zagel"))
        self.statusButton.setToolTip(_translate("ChatRoomWin", "Stories"))
        self.newChatButton.setToolTip(_translate("ChatRoomWin", "Add ChatRoom"))
        self.searchButton.setToolTip(_translate("ChatRoomWin", "Search"))
        self.searchLine.setPlaceholderText(_translate("ChatRoomWin", "Search"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatRoomWin = QtWidgets.QWidget()
    ui = Ui_ChatRoomWin()
    ui.setupUi(ChatRoomWin)
    ChatRoomWin.show()
    sys.exit(app.exec_())
