# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatRoomUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoom(object):
    def setupUi(self, ChatRoom):
        ChatRoom.setObjectName("ChatRoom")
        ChatRoom.resize(617, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChatRoom.sizePolicy().hasHeightForWidth())
        ChatRoom.setSizePolicy(sizePolicy)
        ChatRoom.setMaximumSize(QtCore.QSize(16777215, 80))
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChatRoom)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(ChatRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: #111b21;\n"
"border-bottom : 1px solid rgba(255,255,255,50);\n"
"}\n"
"\n"
"QPushButton#chatRoomButton{\n"
"background-color : rgba(0,0,0,0);\n"
"color : rgba(255,255,255,230);\n"
"}\n"
"QPushButton#chatRoomButton:pressed{\n"
"background-color : rgba(255,255,255,50);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chatRoomPhoto = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatRoomPhoto.sizePolicy().hasHeightForWidth())
        self.chatRoomPhoto.setSizePolicy(sizePolicy)
        self.chatRoomPhoto.setMinimumSize(QtCore.QSize(60, 60))
        self.chatRoomPhoto.setStyleSheet("border-image:url(:/newPrefix/Icons/Screenshot_20211206_113109.jpg);\n"
"border-radius: 30px;")
        self.chatRoomPhoto.setText("")
        self.chatRoomPhoto.setObjectName("chatRoomPhoto")
        self.horizontalLayout_2.addWidget(self.chatRoomPhoto)
        self.chatRoomButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatRoomButton.sizePolicy().hasHeightForWidth())
        self.chatRoomButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chatRoomButton.setFont(font)
        self.chatRoomButton.setStyleSheet("")
        self.chatRoomButton.setObjectName("chatRoomButton")
        self.horizontalLayout_2.addWidget(self.chatRoomButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.msgCounter = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgCounter.sizePolicy().hasHeightForWidth())
        self.msgCounter.setSizePolicy(sizePolicy)
        self.msgCounter.setMinimumSize(QtCore.QSize(26, 26))
        self.msgCounter.setMaximumSize(QtCore.QSize(26, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.msgCounter.setFont(font)
        self.msgCounter.setStyleSheet("background-color : #00a884;\n"
"color : white;\n"
"border-radius : 13px;")
        self.msgCounter.setText("")
        self.msgCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.msgCounter.setObjectName("msgCounter")
        self.horizontalLayout_2.addWidget(self.msgCounter)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ChatRoom)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom)

    def retranslateUi(self, ChatRoom):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom.setWindowTitle(_translate("ChatRoom", "Form"))
        self.chatRoomButton.setText(_translate("ChatRoom", "DataStructure"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatRoom = QtWidgets.QWidget()
    ui = Ui_ChatRoom()
    ui.setupUi(ChatRoom)
    ChatRoom.show()
    sys.exit(app.exec_())
