# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContactUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contact(object):
    def setupUi(self, Contact):
        Contact.setObjectName("Contact")
        Contact.resize(631, 70)
        Contact.setMinimumSize(QtCore.QSize(0, 70))
        Contact.setMaximumSize(QtCore.QSize(16777215, 70))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Contact)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contact = QtWidgets.QFrame(Contact)
        self.contact.setMinimumSize(QtCore.QSize(0, 70))
        self.contact.setMaximumSize(QtCore.QSize(16777215, 70))
        self.contact.setStyleSheet("background-color:#111b21;\n"
"\n"
"")
        self.contact.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contact.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contact.setObjectName("contact")
        self.gridLayout = QtWidgets.QGridLayout(self.contact)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.contactphoto = QtWidgets.QLabel(self.contact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactphoto.sizePolicy().hasHeightForWidth())
        self.contactphoto.setSizePolicy(sizePolicy)
        self.contactphoto.setMinimumSize(QtCore.QSize(50, 50))
        self.contactphoto.setMaximumSize(QtCore.QSize(50, 50))
        self.contactphoto.setStyleSheet("border-image:url(:/newPrefix/Icons/clipart4208228.png);\n"
"border-radius:25px;")
        self.contactphoto.setText("")
        self.contactphoto.setObjectName("contactphoto")
        self.gridLayout.addWidget(self.contactphoto, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.contact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"                font-size: 12px;\n"
"            }\n"
"\n"
"            QCheckBox::indicator {\n"
"                width: 10px;\n"
"                height: 10px;\n"
"                border: 2px solid #00a884;\n"
"                 border-radius:6px;\n"
"            }\n"
"\n"
"            QCheckBox::indicator:checked {\n"
"             background-color: #00a884;\n"
"            }\n"
"\n"
"            QCheckBox::indicator:unchecked {\n"
"                background-color: rgba(0,0,0,0);\n"
"            }\n"
"\n"
"           ")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 2, 1)
        self.Aboutcontact = QtWidgets.QLabel(self.contact)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Aboutcontact.setFont(font)
        self.Aboutcontact.setStyleSheet("color:rgba(255,255,255,150);\n"
"padding-left:10px;")
        self.Aboutcontact.setObjectName("Aboutcontact")
        self.gridLayout.addWidget(self.Aboutcontact, 1, 2, 1, 3)
        self.Namecontact = QtWidgets.QLabel(self.contact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Namecontact.sizePolicy().hasHeightForWidth())
        self.Namecontact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Namecontact.setFont(font)
        self.Namecontact.setStyleSheet("color:rgba(255,255,255,240);\n"
"padding-left:10px;")
        self.Namecontact.setObjectName("Namecontact")
        self.gridLayout.addWidget(self.Namecontact, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.contact)

        self.retranslateUi(Contact)
        QtCore.QMetaObject.connectSlotsByName(Contact)

    def retranslateUi(self, Contact):
        _translate = QtCore.QCoreApplication.translate
        Contact.setWindowTitle(_translate("Contact", "Form"))
        self.Aboutcontact.setText(_translate("Contact", "لا ابرح حتي ابلغ "))
        self.Namecontact.setText(_translate("Contact", "Mohamed Zakria "))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Contact = QtWidgets.QWidget()
    ui = Ui_Contact()
    ui.setupUi(Contact)
    Contact.show()
    sys.exit(app.exec_())
