# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContactWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactWindow(object):
    def setupUi(self, ContactWindow):
        ContactWindow.setObjectName("ContactWindow")
        ContactWindow.resize(410, 787)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ContactWindow)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(ContactWindow)
        self.widget.setMinimumSize(QtCore.QSize(410, 0))
        self.widget.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgba(0,0,0,0);\n"
"    width: 7px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #00a884; /* whatsapp color */\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: #00a884;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #00a884;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #00a884;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: #008b6d;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newChatBar = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newChatBar.sizePolicy().hasHeightForWidth())
        self.newChatBar.setSizePolicy(sizePolicy)
        self.newChatBar.setMinimumSize(QtCore.QSize(0, 85))
        self.newChatBar.setMaximumSize(QtCore.QSize(16777215, 85))
        self.newChatBar.setStyleSheet("background-color:#202c33;\n"
"\n"
"")
        self.newChatBar.setObjectName("newChatBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.newChatBar)
        self.horizontalLayout.setContentsMargins(10, 15, 10, 15)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exitContact = QtWidgets.QPushButton(self.newChatBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitContact.sizePolicy().hasHeightForWidth())
        self.exitContact.setSizePolicy(sizePolicy)
        self.exitContact.setMaximumSize(QtCore.QSize(70, 70))
        self.exitContact.setStyleSheet("background-color : rgba(0,0,0,0);")
        self.exitContact.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/55ovjpq6bo1dpbpq69e2m1lvrq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitContact.setIcon(icon)
        self.exitContact.setIconSize(QtCore.QSize(25, 25))
        self.exitContact.setObjectName("exitContact")
        self.horizontalLayout.addWidget(self.exitContact)
        self.selectContact = QtWidgets.QLabel(self.newChatBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectContact.sizePolicy().hasHeightForWidth())
        self.selectContact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.selectContact.setFont(font)
        self.selectContact.setStyleSheet("color: rgba(255,255,255,200);")
        self.selectContact.setObjectName("selectContact")
        self.horizontalLayout.addWidget(self.selectContact)
        self.createRoomButton = QtWidgets.QPushButton(self.newChatBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.createRoomButton.sizePolicy().hasHeightForWidth())
        self.createRoomButton.setSizePolicy(sizePolicy)
        self.createRoomButton.setMinimumSize(QtCore.QSize(150, 60))
        self.createRoomButton.setMaximumSize(QtCore.QSize(16777215, 109))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.createRoomButton.setFont(font)
        self.createRoomButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #00a884;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00a884;\n"
"}\n"
"")
        self.createRoomButton.setObjectName("createRoomButton")
        self.horizontalLayout.addWidget(self.createRoomButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.newChatBar)
        self.contactFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactFrame.sizePolicy().hasHeightForWidth())
        self.contactFrame.setSizePolicy(sizePolicy)
        self.contactFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.contactFrame.setStyleSheet("background-color:#111b21;\n"
"")
        self.contactFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contactFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contactFrame.setObjectName("contactFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contactFrame)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chatRoomFrame = QtWidgets.QFrame(self.contactFrame)
        self.chatRoomFrame.setStyleSheet("QWidget#chatRoomFrame{\n"
"    background-color: #111b21;\n"
"}")
        self.chatRoomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatRoomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatRoomFrame.setObjectName("chatRoomFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chatRoomFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchContactsFrame = QtWidgets.QFrame(self.chatRoomFrame)
        self.searchContactsFrame.setStyleSheet("QFrame#searchContactsFrame{\n"
"background-color : #222d34;\n"
"margin-left : 10px;\n"
"margin-right : 10px;\n"
"margin-top : 7px;\n"
"margin-bottom : 7px;\n"
"border-radius : 15px;\n"
"}\n"
"QPushButton{\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QLineEdit{\n"
"background-color : rgba(0,0,0,0);\n"
"color : rgba(255,255,255,200);\n"
"border:None;\n"
"}")
        self.searchContactsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchContactsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchContactsFrame.setObjectName("searchContactsFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.searchContactsFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchButton = QtWidgets.QPushButton(self.searchContactsFrame)
        self.searchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon1)
        self.searchButton.setIconSize(QtCore.QSize(20, 20))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.searchLine = QtWidgets.QLineEdit(self.searchContactsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLine.sizePolicy().hasHeightForWidth())
        self.searchLine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchLine.setFont(font)
        self.searchLine.setObjectName("searchLine")
        self.horizontalLayout_3.addWidget(self.searchLine)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout_3.addWidget(self.searchContactsFrame)
        self.frame = QtWidgets.QFrame(self.chatRoomFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addContact = QtWidgets.QPushButton(self.frame)
        self.addContact.setStyleSheet("background-color : rgba(0,0,0,0);\n"
"image: url(:/newPrefix/Daco_4818361.png);\n"
"")
        self.addContact.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/Daco_4818361.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addContact.setIcon(icon2)
        self.addContact.setIconSize(QtCore.QSize(30, 30))
        self.addContact.setObjectName("addContact")
        self.horizontalLayout_4.addWidget(self.addContact)
        self.newContact = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newContact.sizePolicy().hasHeightForWidth())
        self.newContact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.newContact.setFont(font)
        self.newContact.setStyleSheet("border:none;\n"
"color:rgba(255,255,255,200);")
        self.newContact.setText("")
        self.newContact.setObjectName("newContact")
        self.horizontalLayout_4.addWidget(self.newContact)
        self.textError = QtWidgets.QLabel(self.frame)
        self.textError.setStyleSheet("color:#b62916;\n"
"")
        self.textError.setText("")
        self.textError.setObjectName("textError")
        self.horizontalLayout_4.addWidget(self.textError)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_4.setStretch(2, 4)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(self.chatRoomFrame)
        self.scrollArea.setStyleSheet("QScrollArea#scrollArea{\n"
"border : none;\n"
"}\n"
"QScrollBar:vertical{\n"
"border:none;\n"
"background-color : rgb(60,60,90);\n"
"width : 10px;\n"
"border-radius : 5px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"color : rgb(0, 168, 132);\n"
"border-radius : 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"color : rgba(255,255,255,200);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.ScrollRooms = QtWidgets.QWidget()
        self.ScrollRooms.setGeometry(QtCore.QRect(0, 0, 397, 544))
        self.ScrollRooms.setStyleSheet("QWidget#ScrollRooms{\n"
"    background-color: #111b21;\n"
"}")
        self.ScrollRooms.setObjectName("ScrollRooms")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ScrollRooms)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.ScrollRooms)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 8)
        self.horizontalLayout_2.addWidget(self.chatRoomFrame)
        self.verticalLayout.addWidget(self.contactFrame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(ContactWindow)
        QtCore.QMetaObject.connectSlotsByName(ContactWindow)

    def retranslateUi(self, ContactWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactWindow.setWindowTitle(_translate("ContactWindow", "Form"))
        self.selectContact.setText(_translate("ContactWindow", "Select Contact"))
        self.createRoomButton.setText(_translate("ContactWindow", "Create"))
        self.searchLine.setPlaceholderText(_translate("ContactWindow", "Search contacts"))
        self.newContact.setPlaceholderText(_translate("ContactWindow", "New Contact"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContactWindow = QtWidgets.QWidget()
    ui = Ui_ContactWindow()
    ui.setupUi(ContactWindow)
    ContactWindow.show()
    sys.exit(app.exec_())
