# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateGroup(object):
    def setupUi(self, CreateGroup):
        CreateGroup.setObjectName("CreateGroup")
        CreateGroup.resize(633, 120)
        CreateGroup.setStyleSheet("QWidget#CreateGroup{\n"
"border-radius : 10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateGroup)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBar = QtWidgets.QWidget(CreateGroup)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 30))
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titleBar.setStyleSheet("QWidget#titleBar{\n"
"background-color : #00a884;\n"
"border : none;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px;\n"
"}\n"
"QPushButton{\n"
"border-radius : 10px;\n"
"}\n"
"")
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.titleBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color : rgba(255,255,255,240);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.max = QtWidgets.QPushButton(self.titleBar)
        self.max.setMinimumSize(QtCore.QSize(20, 20))
        self.max.setMaximumSize(QtCore.QSize(20, 20))
        self.max.setStyleSheet("QPushButton{\n"
"background-color :rgba(240, 136, 0 ,255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : rgba(240 ,136, 0, 200);\n"
"}")
        self.max.setText("")
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.close = QtWidgets.QPushButton(self.titleBar)
        self.close.setMinimumSize(QtCore.QSize(20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("QPushButton{\n"
"background-color : rgba(240,0,0,255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : rgb(200, 0, 0);\n"
"}")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayout.addWidget(self.titleBar)
        self.widget = QtWidgets.QWidget(CreateGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: rgb(32, 44, 51);\n"
"}\n"
"\n"
"QPushButton#chatRoomButton{\n"
"background-color : rgba(0,0,0,0);\n"
"color : rgba(255,255,255,230);\n"
"}\n"
"QPushButton#chatRoomButton:pressed{\n"
"background-color : rgba(255,255,255,50);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupPhoto = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupPhoto.sizePolicy().hasHeightForWidth())
        self.groupPhoto.setSizePolicy(sizePolicy)
        self.groupPhoto.setMinimumSize(QtCore.QSize(70, 70))
        self.groupPhoto.setMaximumSize(QtCore.QSize(70, 70))
        self.groupPhoto.setStyleSheet("border-image :url(:/newPrefix/Icons/clipart4208228.png);\n"
"border-radius : 35px;")
        self.groupPhoto.setText("")
        self.groupPhoto.setObjectName("groupPhoto")
        self.horizontalLayout_2.addWidget(self.groupPhoto)
        self.groupName = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupName.sizePolicy().hasHeightForWidth())
        self.groupName.setSizePolicy(sizePolicy)
        self.groupName.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupName.setFont(font)
        self.groupName.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid #00a884;\n"
"color : white;\n"
"border-radius: 0px;")
        self.groupName.setText("")
        self.groupName.setObjectName("groupName")
        self.horizontalLayout_2.addWidget(self.groupName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.createRoomButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.createRoomButton.sizePolicy().hasHeightForWidth())
        self.createRoomButton.setSizePolicy(sizePolicy)
        self.createRoomButton.setMinimumSize(QtCore.QSize(90, 50))
        self.createRoomButton.setMaximumSize(QtCore.QSize(90, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.createRoomButton.setFont(font)
        self.createRoomButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #00a884;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00a884;\n"
"}\n"
"")
        self.createRoomButton.setObjectName("createRoomButton")
        self.horizontalLayout_2.addWidget(self.createRoomButton)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(CreateGroup)
        QtCore.QMetaObject.connectSlotsByName(CreateGroup)

    def retranslateUi(self, CreateGroup):
        _translate = QtCore.QCoreApplication.translate
        CreateGroup.setWindowTitle(_translate("CreateGroup", "Form"))
        self.label.setText(_translate("CreateGroup", "  Create Group"))
        self.groupName.setPlaceholderText(_translate("CreateGroup", "Group Name...."))
        self.createRoomButton.setText(_translate("CreateGroup", "Create"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateGroup = QtWidgets.QWidget()
    ui = Ui_CreateGroup()
    ui.setupUi(CreateGroup)
    CreateGroup.show()
    sys.exit(app.exec_())
