# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainStoryUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainStoriesWindow(object):
    def setupUi(self, MainStoriesWindow):
        MainStoriesWindow.setObjectName("MainStoriesWindow")
        MainStoriesWindow.resize(1124, 714)
        MainStoriesWindow.setStyleSheet("background-color: rgb(11, 20, 26);")
        self.gridLayout = QtWidgets.QGridLayout(MainStoriesWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainStoriesWindowWidget = QtWidgets.QWidget(MainStoriesWindow)
        self.MainStoriesWindowWidget.setStyleSheet("QWidget#widget\n"
"{\n"
"background-color: rgb(30, 38, 44);}\n"
"\n"
"QScrollArea{\n"
"border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: #0b141b;\n"
"width: 18px;\n"
"border-radius: 0px;\n"
"margin: 10px 0px 10px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background-color: #00a884;\n"
"border: none;\n"
"border-radius: 9px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertica, QScrollBar::down-arrow:vertical{\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical , QScrollBar::sub-page:vertical{\n"
"background: none;\n"
"}")
        self.MainStoriesWindowWidget.setObjectName("MainStoriesWindowWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.MainStoriesWindowWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DisplayGridLayout = QtWidgets.QGridLayout()
        self.DisplayGridLayout.setObjectName("DisplayGridLayout")
        self.Display = QtWidgets.QLabel(self.MainStoriesWindowWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Display.setFont(font)
        self.Display.setAutoFillBackground(False)
        self.Display.setStyleSheet("border-image:url(:/newPrefix/Icons/WhatsappWebStoryPage.jpg);\n"
"font: 14pt \"Arial\";\n"
"color: white;")
        self.Display.setText("")
        self.Display.setScaledContents(False)
        self.Display.setAlignment(QtCore.Qt.AlignCenter)
        self.Display.setWordWrap(False)
        self.Display.setObjectName("Display")
        self.DisplayGridLayout.addWidget(self.Display, 1, 0, 1, 1)
        self.StoryDuration = QtWidgets.QProgressBar(self.MainStoriesWindowWidget)
        self.StoryDuration.setStyleSheet("QProgressBar{\n"
"border: none;\n"
"background-color: #0b141b;\n"
"height: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: #00a884;\n"
"}")
        self.StoryDuration.setProperty("value", 0)
        self.StoryDuration.setTextVisible(False)
        self.StoryDuration.setObjectName("StoryDuration")
        self.DisplayGridLayout.addWidget(self.StoryDuration, 0, 0, 1, 1)
        self.DisplayGridLayout.setRowStretch(0, 11)
        self.gridLayout_3.addLayout(self.DisplayGridLayout, 0, 1, 1, 1)
        self.StoriesAndOptionsGridLayout = QtWidgets.QWidget(self.MainStoriesWindowWidget)
        self.StoriesAndOptionsGridLayout.setStyleSheet("\n"
"QWidget#widget\n"
"{\n"
"background-color: rgb(30, 38, 44);}\n"
"")
        self.StoriesAndOptionsGridLayout.setObjectName("StoriesAndOptionsGridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.StoriesAndOptionsGridLayout)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.StoriesAndOptionsGridLayout)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: #0b141b;\n"
"width: 18px;\n"
"border-radius: 0px;\n"
"margin: 10px 0px 10px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background-color: #00a884;\n"
"border: none;\n"
"border-radius: 9px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertica, QScrollBar::down-arrow:vertical{\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical , QScrollBar::sub-page:vertical{\n"
"background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 596))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(30, 38, 44);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaContent = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.Spacer = QtWidgets.QPushButton(self.StoriesAndOptionsGridLayout)
        self.Spacer.setMinimumSize(QtCore.QSize(8, 1))
        self.Spacer.setMaximumSize(QtCore.QSize(16777215, 2))
        self.Spacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Spacer.setStyleSheet("QPushButton#Spacer\n"
"\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Spacer.setText("")
        self.Spacer.setObjectName("Spacer")
        self.gridLayout_4.addWidget(self.Spacer, 1, 0, 1, 1)
        self.OptionsGridLayout = QtWidgets.QWidget(self.StoriesAndOptionsGridLayout)
        self.OptionsGridLayout.setStyleSheet("background-color: rgb(30, 38, 44);")
        self.OptionsGridLayout.setObjectName("OptionsGridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.OptionsGridLayout)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setHorizontalSpacing(5)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.BackButtonVerticalLayout = QtWidgets.QVBoxLayout()
        self.BackButtonVerticalLayout.setObjectName("BackButtonVerticalLayout")
        self.Back = QtWidgets.QPushButton(self.OptionsGridLayout)
        self.Back.setMinimumSize(QtCore.QSize(44, 44))
        self.Back.setMaximumSize(QtCore.QSize(44, 44))
        self.Back.setStyleSheet("QPushButton#Back{\n"
"border: none;\n"
"}")
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/55ovjpq6bo1dpbpq69e2m1lvrq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(26, 26))
        self.Back.setObjectName("Back")
        self.BackButtonVerticalLayout.addWidget(self.Back)
        self.gridLayout_5.addLayout(self.BackButtonVerticalLayout, 0, 0, 1, 1)
        self.AddStoriesVerticalLayout = QtWidgets.QVBoxLayout()
        self.AddStoriesVerticalLayout.setObjectName("AddStoriesVerticalLayout")
        self.AddStoryText = QtWidgets.QPushButton(self.OptionsGridLayout)
        self.AddStoryText.setMinimumSize(QtCore.QSize(44, 44))
        self.AddStoryText.setMaximumSize(QtCore.QSize(44, 44))
        self.AddStoryText.setStyleSheet("QPushButton#AddStoryText{\n"
"border: none;\n"
"border-radius: 22px;\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton#AddStoryText:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QPushButton#AddStoryText:pressed{\n"
"background-color: #00a884;\n"
"}")
        self.AddStoryText.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/circle-compose-draw-edit-write-icon-728133.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddStoryText.setIcon(icon1)
        self.AddStoryText.setIconSize(QtCore.QSize(40, 40))
        self.AddStoryText.setObjectName("AddStoryText")
        self.AddStoriesVerticalLayout.addWidget(self.AddStoryText)
        self.AddStoryImage = QtWidgets.QPushButton(self.OptionsGridLayout)
        self.AddStoryImage.setMinimumSize(QtCore.QSize(44, 44))
        self.AddStoryImage.setMaximumSize(QtCore.QSize(44, 44))
        self.AddStoryImage.setStyleSheet("QPushButton#AddStoryImage{\n"
"border: none;\n"
"border-radius: 22px;\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton#AddStoryImage:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QPushButton#AddStoryImage:pressed{\n"
"background-color: #00a884;\n"
"}")
        self.AddStoryImage.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddStoryImage.setIcon(icon2)
        self.AddStoryImage.setIconSize(QtCore.QSize(40, 40))
        self.AddStoryImage.setObjectName("AddStoryImage")
        self.AddStoriesVerticalLayout.addWidget(self.AddStoryImage)
        self.gridLayout_5.addLayout(self.AddStoriesVerticalLayout, 0, 3, 1, 1)
        self.Status = QtWidgets.QLabel(self.OptionsGridLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Status.setFont(font)
        self.Status.setStyleSheet("color: white;")
        self.Status.setObjectName("Status")
        self.gridLayout_5.addWidget(self.Status, 0, 2, 1, 1)
        self.OwnerImage = QtWidgets.QLabel(self.OptionsGridLayout)
        self.OwnerImage.setMinimumSize(QtCore.QSize(80, 80))
        self.OwnerImage.setMaximumSize(QtCore.QSize(80, 80))
        self.OwnerImage.setStyleSheet("border-image: url(:/newPrefix/Icons/1.jpg);\n"
"border-radius: 40;")
        self.OwnerImage.setText("")
        self.OwnerImage.setObjectName("OwnerImage")
        self.gridLayout_5.addWidget(self.OwnerImage, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.OptionsGridLayout, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 2)
        self.gridLayout_4.setRowStretch(2, 8)
        self.gridLayout_3.addWidget(self.StoriesAndOptionsGridLayout, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 6)
        self.gridLayout_3.setColumnStretch(1, 11)
        self.gridLayout.addWidget(self.MainStoriesWindowWidget, 0, 0, 1, 1)

        self.retranslateUi(MainStoriesWindow)
        QtCore.QMetaObject.connectSlotsByName(MainStoriesWindow)

    def retranslateUi(self, MainStoriesWindow):
        _translate = QtCore.QCoreApplication.translate
        MainStoriesWindow.setWindowTitle(_translate("MainStoriesWindow", "Form"))
        self.Back.setToolTip(_translate("MainStoriesWindow", "Back"))
        self.AddStoryText.setToolTip(_translate("MainStoriesWindow", "Add Text Story"))
        self.AddStoryImage.setToolTip(_translate("MainStoriesWindow", "Add Image Story"))
        self.Status.setText(_translate("MainStoriesWindow", "  My Status"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainStoriesWindow = QtWidgets.QWidget()
    ui = Ui_MainStoriesWindow()
    ui.setupUi(MainStoriesWindow)
    MainStoriesWindow.show()
    sys.exit(app.exec_())
