# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Message_2(object):
    def setupUi(self, Message_2):
        Message_2.setObjectName("Message_2")
        Message_2.resize(365, 260)
        Message_2.setMinimumSize(QtCore.QSize(150, 100))
        Message_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Message_2.setStyleSheet("QLabel#msg\n"
"{\n"
"background-color: rgb(7, 94, 84);\n"
"color: #fff;\n"
"border-top-left-radius: 0.7em;\n"
"border-top-right-radius: 0.1em;\n"
"margin-top: 1.1em;\n"
"margin-right: 1em;\n"
"margin-left: 1em;\n"
"}\n"
"\n"
"QLabel#time\n"
"{\n"
"background-color: rgb(7, 94, 84);\n"
"color: #fff;\n"
"margin-right: 1em;\n"
"margin-left: 1em;\n"
"margin-bottom: 1em;\n"
"border-bottom-right-radius: 0.7em;\n"
"border-bottom-left-radius: 0.7em;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Message_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.containter = QtWidgets.QWidget(Message_2)
        self.containter.setMinimumSize(QtCore.QSize(0, 0))
        self.containter.setMaximumSize(QtCore.QSize(0, 0))
        self.containter.setObjectName("containter")
        self.gridLayout = QtWidgets.QGridLayout(self.containter)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Message_frame = QtWidgets.QFrame(self.containter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Message_frame.sizePolicy().hasHeightForWidth())
        self.Message_frame.setSizePolicy(sizePolicy)
        self.Message_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.Message_frame.setMaximumSize(QtCore.QSize(0, 0))
        self.Message_frame.setStyleSheet("border:none;\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.Message_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Message_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Message_frame.setObjectName("Message_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Message_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.msg = QtWidgets.QLabel(self.Message_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg.sizePolicy().hasHeightForWidth())
        self.msg.setSizePolicy(sizePolicy)
        self.msg.setMinimumSize(QtCore.QSize(70, 70))
        self.msg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.msg.setFont(font)
        self.msg.setStyleSheet("")
        self.msg.setTextFormat(QtCore.Qt.AutoText)
        self.msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg.setObjectName("msg")
        self.gridLayout_4.addWidget(self.msg, 0, 0, 1, 1)
        self.time = QtWidgets.QLabel(self.Message_frame)
        self.time.setMinimumSize(QtCore.QSize(150, 0))
        self.time.setMaximumSize(QtCore.QSize(16777215, 34))
        self.time.setStyleSheet("")
        self.time.setObjectName("time")
        self.gridLayout_4.addWidget(self.time, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.Message_frame, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.containter, 0, 0, 1, 1)

        self.retranslateUi(Message_2)
        QtCore.QMetaObject.connectSlotsByName(Message_2)

    def retranslateUi(self, Message_2):
        _translate = QtCore.QCoreApplication.translate
        Message_2.setWindowTitle(_translate("Message_2", "Form"))
        self.msg.setText(_translate("Message_2", "bokra bokra?"))
        self.time.setText(_translate("Message_2", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Message_2 = QtWidgets.QWidget()
    ui = Ui_Message_2()
    ui.setupUi(Message_2)
    Message_2.show()
    sys.exit(app.exec_())
