# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProfileSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profileSetting(object):
    def setupUi(self, profileSetting):
        profileSetting.setObjectName("profileSetting")
        profileSetting.resize(907, 651)
        self.horizontalLayout = QtWidgets.QHBoxLayout(profileSetting)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profile = QtWidgets.QWidget(profileSetting)
        self.profile.setObjectName("profile")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.profile)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ProfileDescription = QtWidgets.QFrame(self.profile)
        self.ProfileDescription.setStyleSheet("QFrame#ProfileDescription{\n"
"background-color : #111b21;\n"
"border-bottom : 1px solid rgba(255,255,255,100);\n"
"}\n"
"QLabel#photo{\n"
"    border-image: url(:/newPrefix/Icons/5a5afbe8-1228-405d-aa18-9fb0a8cade25.jpg);\n"
"    border-radius : 100px;\n"
"}\n"
"QFrame#profileTitle{\n"
"    background-color: #202c33;\n"
"}\n"
"QPushButton#editPhotoButton{\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton#editPhotoButton:hover{\n"
"background-color : rgba(0,0,0,100);\n"
"}\n"
"QPushButton#editAboutButton{\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton#editAboutButton:hover{\n"
"background-color : rgba(0,0,0,100);\n"
"}\n"
"QLineEdit#about{\n"
"background-color : rgba(0,0,0,0);\n"
"color  : rgba(255,255,255,200);\n"
"border : none;\n"
"}\n"
"")
        self.ProfileDescription.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProfileDescription.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProfileDescription.setObjectName("ProfileDescription")
        self.gridLayout = QtWidgets.QGridLayout(self.ProfileDescription)
        self.gridLayout.setContentsMargins(0, 0, 0, 20)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 7, 1, 1)
        self.editAboutButton = QtWidgets.QPushButton(self.ProfileDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAboutButton.sizePolicy().hasHeightForWidth())
        self.editAboutButton.setSizePolicy(sizePolicy)
        self.editAboutButton.setMinimumSize(QtCore.QSize(25, 25))
        self.editAboutButton.setMaximumSize(QtCore.QSize(25, 25))
        self.editAboutButton.setStyleSheet("")
        self.editAboutButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/pencil-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editAboutButton.setIcon(icon)
        self.editAboutButton.setIconSize(QtCore.QSize(25, 25))
        self.editAboutButton.setObjectName("editAboutButton")
        self.gridLayout.addWidget(self.editAboutButton, 1, 6, 1, 1)
        self.profilephoto = QtWidgets.QFrame(self.ProfileDescription)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        self.profilephoto.setFont(font)
        self.profilephoto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profilephoto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profilephoto.setObjectName("profilephoto")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.profilephoto)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.editPhotoButton = QtWidgets.QPushButton(self.profilephoto)
        self.editPhotoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPhotoButton.setIcon(icon1)
        self.editPhotoButton.setIconSize(QtCore.QSize(50, 50))
        self.editPhotoButton.setObjectName("editPhotoButton")
        self.gridLayout_2.addWidget(self.editPhotoButton, 3, 1, 1, 1)
        self.profileTitle = QtWidgets.QFrame(self.profilephoto)
        self.profileTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.profileTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.profileTitle.setStyleSheet("")
        self.profileTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileTitle.setObjectName("profileTitle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.profileTitle)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.profileTitle)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setStyleSheet("background-color : rgba(0,0,0,0);")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/55ovjpq6bo1dpbpq69e2m1lvrq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.profileTitle)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left: 40px;\n"
"color : rgba(255,255,255,255);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 7)
        self.gridLayout_2.addWidget(self.profileTitle, 0, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 2, 1, 1)
        self.photo = QtWidgets.QLabel(self.profilephoto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo.sizePolicy().hasHeightForWidth())
        self.photo.setSizePolicy(sizePolicy)
        self.photo.setMinimumSize(QtCore.QSize(200, 200))
        self.photo.setMaximumSize(QtCore.QSize(200, 200))
        self.photo.setStyleSheet("border-image: url(:/newPrefix/Icons/Screenshot_20211206_113109.jpg);\n"
"border-radius : 100px;\n"
"")
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.gridLayout_2.addWidget(self.photo, 1, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.profilephoto, 0, 0, 1, 9)
        self.label_8 = QtWidgets.QLabel(self.ProfileDescription)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color : #00a884;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.about = QtWidgets.QLineEdit(self.ProfileDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about.sizePolicy().hasHeightForWidth())
        self.about.setSizePolicy(sizePolicy)
        self.about.setMinimumSize(QtCore.QSize(500, 0))
        self.about.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.about.setFont(font)
        self.about.setStyleSheet("")
        self.about.setPlaceholderText("")
        self.about.setObjectName("about")
        self.gridLayout.addWidget(self.about, 1, 3, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.verticalLayout.addWidget(self.ProfileDescription)
        self.ProfileSetting = QtWidgets.QFrame(self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ProfileSetting.setFont(font)
        self.ProfileSetting.setStyleSheet("QFrame#ProfileSetting{\n"
"background-color : #111b21;\n"
"}\n"
"QLabel{\n"
"color : #00a884;\n"
"}\n"
"QRadioButton{\n"
"color : rgba(255,255,255,160);\n"
"padding-left : 20px;\n"
"}\n"
"QRadioButton::indicator {\n"
"width: 11px;\n"
"height: 11px;\n"
"border-radius: 5px;\n"
"}\n"
"QRadioButton::indicator::unchecked{ \n"
"border: 3px solid; \n"
"border-color: #00a884;\n"
"border-radius: 5px;\n"
"background-color: rgba(0,0,0,0); \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"border: 3px solid; \n"
"border-color: #00a884;\n"
"border-radius: 6px;\n"
"background-color: #00a884; \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,255,255,170);\n"
"color:rgba(255, 255, 255, 170);\n"
"border-radius: 0px;\n"
"margin-left : 20px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #00a884;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00a884;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #005c4b;\n"
"}")
        self.ProfileSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProfileSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProfileSetting.setObjectName("ProfileSetting")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ProfileSetting)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mydata = QtWidgets.QFrame(self.ProfileSetting)
        self.mydata.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mydata.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mydata.setObjectName("mydata")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mydata)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PasswordFrame = QtWidgets.QFrame(self.mydata)
        self.PasswordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PasswordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PasswordFrame.setObjectName("PasswordFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.PasswordFrame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.PasswordFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.PasswordFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password.setObjectName("password")
        self.gridLayout_5.addWidget(self.password, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 2, 1)
        self.gridLayout_5.setColumnStretch(0, 5)
        self.gridLayout_5.setColumnStretch(1, 5)
        self.gridLayout_3.addWidget(self.PasswordFrame, 2, 0, 1, 1)
        self.NameFrame = QtWidgets.QFrame(self.mydata)
        self.NameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NameFrame.setObjectName("NameFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.NameFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.NameFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.firstName = QtWidgets.QLineEdit(self.NameFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstName.sizePolicy().hasHeightForWidth())
        self.firstName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName.setFont(font)
        self.firstName.setObjectName("firstName")
        self.gridLayout_4.addWidget(self.firstName, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.NameFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 1, 1, 1)
        self.lastName = QtWidgets.QLineEdit(self.NameFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastName.sizePolicy().hasHeightForWidth())
        self.lastName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName.setFont(font)
        self.lastName.setObjectName("lastName")
        self.gridLayout_4.addWidget(self.lastName, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.NameFrame, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.mydata, 1, 1, 1, 1)
        self.SettingTitle = QtWidgets.QFrame(self.ProfileSetting)
        self.SettingTitle.setStyleSheet("QFrame#frame_2{\n"
"\n"
"}\n"
"QLabel#settingsTitle{\n"
"color : #00a884;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"")
        self.SettingTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SettingTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingTitle.setObjectName("SettingTitle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SettingTitle)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.SettingTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-image: url(:/newPrefix/Icons/settings_green (1).png);\n"
"color : rgba(0,0,0,0);\n"
"padding-left : 100px;\n"
"padding-right : 10px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.settingsTitle = QtWidgets.QLabel(self.SettingTitle)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settingsTitle.setFont(font)
        self.settingsTitle.setStyleSheet("padding-left : 7px;")
        self.settingsTitle.setObjectName("settingsTitle")
        self.horizontalLayout_3.addWidget(self.settingsTitle)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.gridLayout_6.addWidget(self.SettingTitle, 0, 0, 1, 2)
        self.VisibilityFrame = QtWidgets.QFrame(self.ProfileSetting)
        self.VisibilityFrame.setStyleSheet("border-right    :1px solid rgba(255,255,255,100);")
        self.VisibilityFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VisibilityFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VisibilityFrame.setObjectName("VisibilityFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.VisibilityFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.VisibilityFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.myContact = QtWidgets.QRadioButton(self.VisibilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myContact.sizePolicy().hasHeightForWidth())
        self.myContact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.myContact.setFont(font)
        self.myContact.setStyleSheet("")
        self.myContact.setIconSize(QtCore.QSize(12, 12))
        self.myContact.setObjectName("myContact")
        self.verticalLayout_2.addWidget(self.myContact)
        self.onlyMe = QtWidgets.QRadioButton(self.VisibilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onlyMe.sizePolicy().hasHeightForWidth())
        self.onlyMe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.onlyMe.setFont(font)
        self.onlyMe.setIconSize(QtCore.QSize(12, 12))
        self.onlyMe.setObjectName("onlyMe")
        self.verticalLayout_2.addWidget(self.onlyMe)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 4)
        self.gridLayout_6.addWidget(self.VisibilityFrame, 1, 0, 1, 1)
        self.RegisterFrame = QtWidgets.QFrame(self.ProfileSetting)
        self.RegisterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RegisterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RegisterFrame.setObjectName("RegisterFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.RegisterFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.saveSetting_2 = QtWidgets.QPushButton(self.RegisterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSetting_2.sizePolicy().hasHeightForWidth())
        self.saveSetting_2.setSizePolicy(sizePolicy)
        self.saveSetting_2.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveSetting_2.setFont(font)
        self.saveSetting_2.setObjectName("saveSetting_2")
        self.horizontalLayout_6.addWidget(self.saveSetting_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_6.addWidget(self.RegisterFrame, 2, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 3)
        self.gridLayout_6.setColumnStretch(1, 7)
        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 8)
        self.verticalLayout.addWidget(self.ProfileSetting)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 5)
        self.horizontalLayout.addWidget(self.profile)

        self.retranslateUi(profileSetting)
        QtCore.QMetaObject.connectSlotsByName(profileSetting)

    def retranslateUi(self, profileSetting):
        _translate = QtCore.QCoreApplication.translate
        profileSetting.setWindowTitle(_translate("profileSetting", "Form"))
        self.label.setText(_translate("profileSetting", "Profile"))
        self.label_8.setText(_translate("profileSetting", "About :   "))
        self.label_7.setText(_translate("profileSetting", "Passswrod :"))
        self.label_5.setText(_translate("profileSetting", "First Name :"))
        self.label_6.setText(_translate("profileSetting", "Last Name :"))
        self.settingsTitle.setText(_translate("profileSetting", "Settings"))
        self.label_3.setText(_translate("profileSetting", "Visibility"))
        self.myContact.setText(_translate("profileSetting", "My Contacts"))
        self.onlyMe.setText(_translate("profileSetting", "Nobody"))
        self.saveSetting_2.setText(_translate("profileSetting", "Save"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    profileSetting = QtWidgets.QWidget()
    ui = Ui_profileSetting()
    ui.setupUi(profileSetting)
    profileSetting.show()
    sys.exit(app.exec_())
