# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StoryTextUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTextStoryWindow(object):
    def setupUi(self, AddTextStoryWindow):
        AddTextStoryWindow.setObjectName("AddTextStoryWindow")
        AddTextStoryWindow.resize(667, 477)
        self.gridLayout = QtWidgets.QGridLayout(AddTextStoryWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.AddTextStoryWindowWidget = QtWidgets.QWidget(AddTextStoryWindow)
        self.AddTextStoryWindowWidget.setStyleSheet("QWidget#AddTextStoryWindowWidget{\n"
"background-color: rgb(38, 44, 58);\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: #0b141b;\n"
"width: 18px;\n"
"border-radius: 0px;\n"
"margin: 10px 0px 10px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background-color: #00a884;\n"
"border: none;\n"
"border-radius: 3px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertica, QScrollBar::down-arrow:vertical{\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical , QScrollBar::sub-page:vertical{\n"
"background: none;\n"
"}")
        self.AddTextStoryWindowWidget.setObjectName("AddTextStoryWindowWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AddTextStoryWindowWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LineEditAndButtonWidget = QtWidgets.QWidget(self.AddTextStoryWindowWidget)
        self.LineEditAndButtonWidget.setObjectName("LineEditAndButtonWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.LineEditAndButtonWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TextEntry = QtWidgets.QPlainTextEdit(self.LineEditAndButtonWidget)
        self.TextEntry.setMinimumSize(QtCore.QSize(0, 60))
        self.TextEntry.setMaximumSize(QtCore.QSize(16777215, 60))
        self.TextEntry.setStyleSheet("QPlainTextEdit{border:none;\n"
"background-color: rgb(54, 69, 79);\n"
"border:6px solid black;\n"
"border-color: rgba(0, 0, 0, 0);\n"
"border-radius: 13px;\n"
"color:rgb(255, 255, 255);\n"
"font-size:19px;\n"
"}\n"
"\n"
"QScrollArea{\n"
"border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: #0b141b;\n"
"width: 18px;\n"
"border-radius: 0px;\n"
"margin: 10px 0px 10px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background-color: #00a884;\n"
"border: none;\n"
"border-radius: 9px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"border: none;\n"
"height: 15px;\n"
"background-color: #00a884;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"border: none;\n"
"height: 10px;\n"
"background-color: #00a884;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed{\n"
"background-color: #00a884;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertica, QScrollBar::down-arrow:vertical{\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical , QScrollBar::sub-page:vertical{\n"
"background: none;\n"
"}")
        self.TextEntry.setTabStopWidth(80)
        self.TextEntry.setObjectName("TextEntry")
        self.gridLayout_3.addWidget(self.TextEntry, 0, 0, 1, 1)
        self.SubmitButton = QtWidgets.QPushButton(self.LineEditAndButtonWidget)
        self.SubmitButton.setMinimumSize(QtCore.QSize(60, 60))
        self.SubmitButton.setMaximumSize(QtCore.QSize(60, 60))
        self.SubmitButton.setStyleSheet("QPushButton#SubmitButton{\n"
"border: none;\n"
"border-radius: 30px;\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton#SubmitButton:hover{\n"
"background-color: #CFD3CE;\n"
"}\n"
"\n"
"QPushButton#SubmitButton:pressed{\n"
"background-color: #00a884;\n"
"}")
        self.SubmitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/WhatsApp Image 2022-05-08 at 2.03.18 AM-modified.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SubmitButton.setIcon(icon)
        self.SubmitButton.setIconSize(QtCore.QSize(55, 55))
        self.SubmitButton.setObjectName("SubmitButton")
        self.gridLayout_3.addWidget(self.SubmitButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.LineEditAndButtonWidget, 1, 0, 1, 1)
        self.BackgroundImageLabel = QtWidgets.QLabel(self.AddTextStoryWindowWidget)
        self.BackgroundImageLabel.setStyleSheet("background-color: rgb(30, 38, 44);\n"
"border-image:url(:/newPrefix/Icons/Screenshot_2022-05-08_230119.png);")
        self.BackgroundImageLabel.setText("")
        self.BackgroundImageLabel.setObjectName("BackgroundImageLabel")
        self.gridLayout_2.addWidget(self.BackgroundImageLabel, 0, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 2)
        self.gridLayout_2.setRowMinimumHeight(1, 8)
        self.gridLayout_2.setRowStretch(0, 12)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout.addWidget(self.AddTextStoryWindowWidget, 0, 0, 1, 1)

        self.retranslateUi(AddTextStoryWindow)
        QtCore.QMetaObject.connectSlotsByName(AddTextStoryWindow)

    def retranslateUi(self, AddTextStoryWindow):
        _translate = QtCore.QCoreApplication.translate
        AddTextStoryWindow.setWindowTitle(_translate("AddTextStoryWindow", "Form"))
        self.TextEntry.setPlaceholderText(_translate("AddTextStoryWindow", "Enter Your Text"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddTextStoryWindow = QtWidgets.QWidget()
    ui = Ui_AddTextStoryWindow()
    ui.setupUi(AddTextStoryWindow)
    AddTextStoryWindow.show()
    sys.exit(app.exec_())
