# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StoryUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Story(object):
    def setupUi(self, Story):
        Story.setObjectName("Story")
        Story.resize(562, 100)
        Story.setMinimumSize(QtCore.QSize(0, 100))
        Story.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gridLayout = QtWidgets.QGridLayout(Story)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.StoryWidget = QtWidgets.QWidget(Story)
        self.StoryWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.StoryWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.StoryWidget.setStyleSheet("background-color: rgb(30, 38, 44);")
        self.StoryWidget.setObjectName("StoryWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.StoryWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PhotoHorizontalLayout = QtWidgets.QHBoxLayout()
        self.PhotoHorizontalLayout.setObjectName("PhotoHorizontalLayout")
        self.PersonalPhoto = QtWidgets.QPushButton(self.StoryWidget)
        self.PersonalPhoto.setMinimumSize(QtCore.QSize(80, 80))
        self.PersonalPhoto.setMaximumSize(QtCore.QSize(70, 70))
        self.PersonalPhoto.setStyleSheet("border-image: url(:/newPrefix/Icons/11.jpg);\n"
"border-radius: 40px;")
        self.PersonalPhoto.setText("")
        self.PersonalPhoto.setIconSize(QtCore.QSize(40, 40))
        self.PersonalPhoto.setObjectName("PersonalPhoto")
        self.PhotoHorizontalLayout.addWidget(self.PersonalPhoto)
        self.horizontalLayout.addLayout(self.PhotoHorizontalLayout)
        self.NameAndDateVerticalLayout = QtWidgets.QVBoxLayout()
        self.NameAndDateVerticalLayout.setSpacing(0)
        self.NameAndDateVerticalLayout.setObjectName("NameAndDateVerticalLayout")
        self.ContactName = QtWidgets.QLabel(self.StoryWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ContactName.setFont(font)
        self.ContactName.setStyleSheet("color: white;")
        self.ContactName.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ContactName.setObjectName("ContactName")
        self.NameAndDateVerticalLayout.addWidget(self.ContactName)
        self.StoryDate = QtWidgets.QLabel(self.StoryWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.StoryDate.setFont(font)
        self.StoryDate.setStyleSheet("color: white;")
        self.StoryDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StoryDate.setObjectName("StoryDate")
        self.NameAndDateVerticalLayout.addWidget(self.StoryDate)
        self.horizontalLayout.addLayout(self.NameAndDateVerticalLayout)
        spacerItem = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.StoryWidget, 0, 0, 1, 1)

        self.retranslateUi(Story)
        QtCore.QMetaObject.connectSlotsByName(Story)

    def retranslateUi(self, Story):
        _translate = QtCore.QCoreApplication.translate
        Story.setWindowTitle(_translate("Story", "Form"))
        self.ContactName.setText(_translate("Story", "Abdelmiged"))
        self.StoryDate.setText(_translate("Story", "today at 12.18 am"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Story = QtWidgets.QWidget()
    ui = Ui_Story()
    ui.setupUi(Story)
    Story.show()
    sys.exit(app.exec_())
